### ISSUE TITLE
Radicale openheid / "Open by design"

### ISSUE THREAD

**Issue by stevenvegt** [nuts-foundation/nuts-webpresence#22]
Veel beslissingen mbt landelijke infra worden achter gesloten deuren gemaakt. Denk aan groepen waarbij je eerst lid van moet worden of notulen die op een Google drive staan achter een wachtwoord. Meetings zijn besloten, voortgang van bepaalde projecten en hun verantwoordelijken zijn onduidelijk etc. Je komt na wat doorvragen vaak wel bij een persoon terecht, maar dan krijg je uiteindelijk alleen een stukje documentatie opgestuurd. 

Gezien de impact die een Nuts voorziening op de zorg heeft is deze aanpak buitengewoon onwenselijk.

Ik geloof dat Nuts hiermee moet breken en een verschil kan maken door op **Radicaal open** wijze te functioren.

Voorbeelden:

* Alle agenda's en notulen van vergaderingen inzichtelijk.
* Alle meetings openbaar via bijv. zoom bij te wonen. 
* Elke vorm van, de planning en voortgang inzichtelijk. Wat wordt er waarom en door wie opgepakt.
* Alle geproduceerde artefacten zoals diagrammen, afbeeldingen, code, etc. online inzichtelijk.

Ik denk dat dit zo belangrijk is dat we dit moeten borgen in onze standpunten en statuten.

**Comment by mw24** [comment]
Alle informatie in de stichting is publiek toegankelijk. Hoe dit wordt georganiseerd hoeven we in mijn beleving niet te beschrijven. Als we er met elkaar voor zorgen dat het ego-gehalte in het bestuur en de RvT niet te groot wordt, dan moet het goed gaat :-)

**Comment by stevenvegt** [comment]
Dan ben ik natuurlijk nu benieuwd waarom je vindt dat we dát niet hoeven te beschrijven maar andere punten zoals "privacy by design vinden we een goed idee" wel.

Volgens mij is er een verschil tussen "alle info is op te vragen" vs "alles zal publiekelijk worden vastgelegd". Door dit expliciet te maken: 
a) onderscheiden we ons van bestaande initiatieven 
b) borgen we dit ook in de toekomst.

Let wel, ik bedoel niet dat we moeten vastleggen "hoe" we dit gaan vastleggen, maar wel dat we "open by design zijn".

**Comment by mw24** [comment]
Dat was mijn eerste zin: Alle informatie in de stichting is publiek toegankelijk. Dat kunnen we dan in de statuten opnemen toch?

**Comment by stevenvegt** [comment]
Check. Dat vastleggen in de statuten op die manier lijkt me goed (begreep niet uit je comment dat je dat bedoelde).

Op de website zou ik er wel meer over willen uitweiden.

**Comment by Timendus** [comment]
> Voorbeelden:
>
> * Alle agenda's en notulen van vergaderingen inzichtelijk.
> * Alle meetings openbaar via bijv. zoom bij te wonen.
> * Elke vorm van, de planning en voortgang inzichtelijk. Wat wordt er waarom en door wie opgepakt.
> * Alle geproduceerde artefacten zoals diagrammen, afbeeldingen, code, etc. online inzichtelijk.

Pfff, weet je hoeveel extra werk je je hiermee op de hals haalt..?

Zeker als je het vastlegt in je statuten. Als je zoiets wilt vastleggen, dan zou ik in de statuten opnemen dat je openheid nastreeft, en dit soort uitwerking hooguit in een huishoudelijk reglement vastleggen. Maar volgens mij waren we het daar al wel over eens.

Ik ben zeker voor openheid en tegen achterkamertjesgebeuren, maar ik heb echt geen zin om voor elke meeting mijn gesprekspartners te moeten uitleggen dat we even een publieke zoom room gaan openen waar vervolgens niemand in meekijkt "omdat dat zo moet".

Of om elk plaatje dat ik half af maak meticuleus te moeten documenteren en op de juiste plek te uploaden. Eindproducten daarintegen: allicht. Wat je niet documenteert / wat niet vindbaar is bestaat niet. Ik heb ook niet voor niks een Creative Commons licentie onder de artikelen op de website geplakt.

De intentie: tof. De voorbeelden die je geeft: gadver.

Agenda's en notulen van de stichtingsbestuursvergaderingen openbaar maken: in beginsel prima. Maar ik kan je garanderen dat we in die vergaderingen niks nuttigs gaan bespreken anders dan het afhameren van de begroting of het goedkeuren van een uitgave. De echte keuzes worden toch gemaakt met een kop koffie.

**Comment by Timendus** [comment]
Volgens mij kunnen we deze inmiddels wel sluiten 😜

Conclusie die ik trek in 2020: we hebben de agenda's en opnames van de Nuts meetings openbaar online staan op [Google Drive](https://drive.google.com/drive/folders/11ULe4y2ePX_xbTijc0bQnsWLSyf_65vy) en [YouTube](https://www.youtube.com/channel/UCJtbrUe2TphkzDi2lPY5yYQ/videos). De links naar de Zoom meetings staan [in de kalender](https://nuts.nl/kalender/). De stichtingsvergaderingen komen amper voor, en zijn nagenoeg alleen gebruikt om nieuwe bestuursleden in te stemmen. De voortgang is te volgen hier op Github en de documentatie staat publiekelijk beschikbaar op [Read the docs](https://nuts-documentation.readthedocs.io/en/latest/).

Volgens mij hebben we die radicale openheid (ondanks mijn tegenstribbelen 😉) aardig bereikt.
